### ISSUE TITLE
Error Conneting to redis via socket 

### ISSUE THREAD

**Issue by ticoombs** [SuperTux88/munin-plugins#1]
Is it possible to do this with the sidekiq_stats plugin?

**Comment by SuperTux88** [comment]
You can set `env.REDIS_URL unix://tmp/sockets/redis.sock` in `/etc/munin/plugin-conf.d/`. Is this what you need?

**Comment by ticoombs** [comment]
@SuperTux88 Yes exactly. Thanks!
